name: PR Checks
on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Run tests
        run: go test ./...
